### Endpoint de teste
POST http://localhost:3003/user/signup
Content-Type: application/json

{
    "name":"pedro",
    "email":"pedro@gmai.com",
    "password":"pedro"
}

###
# @name login
POST http://localhost:3003/user/login
Content-Type: application/json

{
    "email":"pedro@gmai.com",
    "password":"pedro"
}

###
@token={{login.response.body.token}}  
POST http://localhost:3003/user/post
Content-Type: application/json
Authorization: {{token}}

{
    "content":"bolsa ou lula."
}

###
GET http://localhost:3003/user/post
Authorization: {{token}}

###  
DELETE http://localhost:3003/user/post/id/6f559097-9a61-4726-9510-36b33b6d0042
Authorization: {{token}}

###



POST http://localhost:3003/user/post/like
Content-Type: application/json
Authorization: {{token}}

{
    "idPostLiked":"297934e4-3100-40cd-a35a-26a5a4962543"
}

# faltou verificar se a curtida ja existe