### Endpoint de teste
POST http://localhost:3003/user/signup
Content-Type: application/json

{
    "name":"abc5",
    "email":"abc5@gmai.com",
    "password":"abc5"
}

###
# @name login
POST http://localhost:3003/user/login
Content-Type: application/json

{
    "email":"abc4@gmai.com",
    "password":"abc4"
}

###
@token={{login.response.body.token}}  
POST http://localhost:3003/user/post
Content-Type: application/json
Authorization: {{token}}

{
    "content":"Tá friozinho hoje."
}

###
GET http://localhost:3003/user/post
Authorization: {{token}}